#!/usr/bin/env bash
# Queries your logged-in Azure CLI and configured OCI CLI, then writes a
# gitignored env file (dba-lab.env) with the real IDs the lab's command
# blocks reference as placeholders. Source that file once per terminal
# session and every later command can use $VAR_NAME instead of pasting IDs.
set -euo pipefail
ENV_FILE="dba-lab.env"
echo "# Auto-generated by scripts/autofill-env.sh — do not commit" > "$ENV_FILE"
echo "" >> "$ENV_FILE"

echo "==> Checking Azure CLI login..."
if az account show >/dev/null 2>&1; then
  AZ_SUB_ID=$(az account show --query "id" -o tsv)
  AZ_SUB_NAME=$(az account show --query "name" -o tsv)
  AZ_TENANT_ID=$(az account show --query "tenantId" -o tsv)
  echo "export AZURE_SUBSCRIPTION_ID=\"$AZ_SUB_ID\"" >> "$ENV_FILE"
  echo "export AZURE_SUBSCRIPTION_NAME=\"$AZ_SUB_NAME\"" >> "$ENV_FILE"
  echo "export AZURE_TENANT_ID=\"$AZ_TENANT_ID\"" >> "$ENV_FILE"
  echo "export AZURE_REGION=\"\${AZURE_REGION:-westus2}\"" >> "$ENV_FILE"
  echo "   found subscription: $AZ_SUB_NAME ($AZ_SUB_ID)"
else
  echo "   ! az login not detected — run 'az login' first, then re-run this script."
fi

echo ""
echo "==> Checking OCI CLI config..."
if oci iam region-subscription list >/dev/null 2>&1; then
  OCI_TENANCY=$(grep -E '^tenancy=' ~/.oci/config | head -1 | cut -d'=' -f2)
  OCI_USER=$(grep -E '^user=' ~/.oci/config | head -1 | cut -d'=' -f2)
  OCI_REGION=$(grep -E '^region=' ~/.oci/config | head -1 | cut -d'=' -f2)
  echo "export OCI_TENANCY_OCID=\"$OCI_TENANCY\"" >> "$ENV_FILE"
  echo "export OCI_USER_OCID=\"$OCI_USER\"" >> "$ENV_FILE"
  echo "export OCI_REGION=\"$OCI_REGION\"" >> "$ENV_FILE"
  echo "export OCI_COMPARTMENT_OCID=\"$OCI_TENANCY\"" >> "$ENV_FILE"
  echo "   found tenancy: $OCI_TENANCY in region $OCI_REGION"

  AD1=$(oci iam availability-domain list --compartment-id "$OCI_TENANCY" \
        --query "data[0].name" --raw-output 2>/dev/null || echo "")
  [ -n "$AD1" ] && echo "export OCI_AD1=\"$AD1\"" >> "$ENV_FILE" && echo "   found AD: $AD1"

  IMG=$(oci compute image list --compartment-id "$OCI_TENANCY" \
        --operating-system "Oracle Linux" --operating-system-version "8" \
        --shape "VM.Standard.E2.1.Micro" --sort-by TIMECREATED --sort-order DESC \
        --query "data[0].id" --raw-output 2>/dev/null || echo "")
  [ -n "$IMG" ] && echo "export OCI_ORACLE_LINUX8_IMAGE_OCID=\"$IMG\"" >> "$ENV_FILE" && echo "   found OL8 image"

  VCN=$(oci network vcn list --compartment-id "$OCI_TENANCY" \
        --query "data[?contains(\"display-name\", 'dba-lab')] | [0].id" --raw-output 2>/dev/null || echo "")
  if [ -n "$VCN" ] && [ "$VCN" != "None" ]; then
    echo "export OCI_VCN_OCID=\"$VCN\"" >> "$ENV_FILE"
    SUBNET=$(oci network subnet list --compartment-id "$OCI_TENANCY" --vcn-id "$VCN" \
             --query "data[0].id" --raw-output 2>/dev/null || echo "")
    [ -n "$SUBNET" ] && [ "$SUBNET" != "None" ] && echo "export OCI_SUBNET_OCID=\"$SUBNET\"" >> "$ENV_FILE" && echo "   found VCN + subnet"
  else
    echo "   no dba-lab VCN yet — expected before Day 3.1; re-run after creating it"
  fi
else
  echo "   ! oci setup config not detected — run that first, then re-run this script."
fi

echo ""
echo "==> Done. Run:  source $ENV_FILE"
